# Generated by Django 5.2.4 on 2025-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0005_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
