# Generated by Django 5.2.4 on 2025-10-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0008_alter_blockeduser_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='info',
            new_name='about',
        ),
    ]
