# Generated by Django 5.2.4 on 2025-07-15 09:44

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_chatgroup_admin_chatgroup_group_chat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='group_chat_name',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='groupchat_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
