# Generated by Django 5.2.4 on 2025-09-11 14:57

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0013_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessages',
            options={'ordering': ['created', 'id']},
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessages',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='groupmessages',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
