# Generated by Django 5.2.4 on 2025-11-25 13:35

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0034_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreadstate',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
